CREATE DATABASE IF NOT EXISTS message_manager;

USE message_manager;

CREATE TABLE IF NOT EXISTS users(
    id_pk INT NOT NULL AUTO_INCREMENT,
    email TEXT NOT NULL UNIQUE,
    alias TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id_pk)
);

CREATE TABLE IF NOT EXISTS messages(
    id_pk INT NOT NULL AUTO_INCREMENT,
    user_id_fk INT NOT NULL,
    head TEXT NOT NULL,
    body TEXT NOT NULL,
    create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id_pk),
    FOREIGN KEY(user_id_fk) REFERENCES users(id_pk)  ON DELETE CASCADE ON UPDATE CASCADE
);
